### ISSUE TITLE
Alternator does not work with AWS skd version 1.11.*

### ISSUE THREAD

**Issue by vasiliy-sarzhynskyi** [mboudreau/Alternator#99]
Hi team,

I tried Alternator (version 0.12.0) as described in README file, but seems it's incompatible with AWS sdk version 1.11.* (I use version 1.11.205).

While creating AlternatorDBClientV2 instance: <code>new AlternatorDBClientV2();</code>
I got the following exception:
<i>NoSuchMethodError: com.amazonaws.transform.JsonErrorUnmarshaller: method <init>()V not found
	at com.michelboudreau.alternatorv2.AlternatorDBClientV2.init(AlternatorDBClientV2.java:106)
	at com.michelboudreau.alternatorv2.AlternatorDBClientV2.<init>(AlternatorDBClientV2.java:100)
	at com.michelboudreau.alternatorv2.AlternatorDBClientV2.<init>(AlternatorDBClientV2.java:95)
</i>
This exception occurs due to non existing JsonErrorUnmarshaller constructor without parameters in AWS skd 1.11.*.

**Comment by mboudreau** [comment]
Hi @vasiliy-sarzhynskyi, 

this project has been deprecated in favor of Amazon's own solution, [DynamoDB Local](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html) or this [docker image](https://hub.docker.com/r/cnadiminti/dynamodb-local/).

No more work will be done on this project as it is now grossly outdated.  Cheers.

**Comment by vasiliy-sarzhynskyi** [comment]
Hi @mboudreau, thanks for your reply.
